Repository BlackOrderMod/BlackOrder, pull requests merged in 2018-11, with the labels that each got.

#42 Updated tool
  .circleci/config.yml
  tools/config_validator.py
  tools/sqf_validator.py
Labels: ignore changelog

#43 Tool change
  .travis.yml
  circle.yml
Labels: ignore changelog

#41 ACE compat: fixed script error on respawn
  optionals/ace_compat/XEH_respawn.sqf
Labels: bug fix

#46 Reverted back to travis
  .travis.yml
  circle.yml
Labels: ignore changelog

#47 Fixed #45
  tools/build.py
  tools/make.cfg
  tools/make.py
Labels: enhancement

#48 Added .vscode
  .gitignore
Labels: ignore changelog

#49 Updated version
  addons/main/script_version.hpp
Labels: ignore changelog
